version: '3'

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  users-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    depends_on:
      - pgadmin

  products-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=products_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    depends_on:
      - users-db

  cart-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cart_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    depends_on:
      - products-db

  orders-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    depends_on:
      - cart-db

  review-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=review_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    depends_on:
      - orders-db

  users-ms:
    build: /users_ms
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    ports:
      - 8001:8001
    depends_on:
      - orders-db

  products-ms:
    build: /products_ms
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    ports:
      - 8002:8002
    depends_on:
      - users-ms

  cart-ms:
    build: /cart_ms
    command: bash -c "flask db upgrade && flask run --host=0.0.0.0 --port=5000"
    ports:
      - 5000:5000
    depends_on:
      - products-ms

  order-ms:
    build: /order_ms
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8003"
    ports:
      - 8003:8003
    depends_on:
      - cart-ms

  review-ms:
    build: /review_ms
    command: bash -c "flask db upgrade && flask run --host=0.0.0.0 --port=5001"
    ports:
      - 5001:5001
    depends_on:
      - order-ms
