# Generated by Django 4.1.7 on 2023-02-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userrole_user_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
    ]
